name: mailbox_notification_system
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_animator: ^3.1.1


flutter:
  uses-material-design: true
  assets:
    - asset/font/
    - asset/gif/
    - asset/jpg/
    - asset/png/

  fonts:
    - family: Mario64
      fonts:
        - asset: asset/font/SuperMario64.ttf
    - family: Mario256
      fonts:
        - asset: asset/font/SuperMario256.ttf
    - family: MarioBros2
      fonts:
        - asset: asset/font/SuperMarioBros2.ttf
